spring:
  application:
    name: observer-spring

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8080